// register the grid component
Vue.component('demo-grid', {
  template: '#grid-template',
  replace: true,
  props: {
    data: Array,
    columns: Array,
    filterKey: String
  },
 /*
 This code is setting up the sortOrders object. 
 The key of each property in this object will be a column name, and the value will be 1.
 This code then sets the sortKey to an empty string, which means that no sorting has been done yet.
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
  data: function () {
    var sortOrders = {}
    this.columns.forEach(function (key) {
      sortOrders[key] = 1
    })
    return {
      sortKey: '',
      sortOrders: sortOrders
    }
  },
  computed: {
 /*
 This code is doing the following.
  It's filtering out all rows that don't contain the filterKey in any of their keys.
  Then it sorts them by sortKey, and then reverses the order if sortOrders[sortKey] is  1 (descending).
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
    filteredData: function () {
      var sortKey = this.sortKey
      var filterKey = this.filterKey && this.filterKey.toLowerCase()
      var order = this.sortOrders[sortKey] || 1
      var data = this.data
      if (filterKey) {
        data = data.filter(function (row) {
          return Object.keys(row).some(function (key) {
            return String(row[key]).toLowerCase().indexOf(filterKey) > -1
          })
        })
      }
      if (sortKey) {
        data = data.slice().sort(function (a, b) {
          a = a[sortKey]
          b = b[sortKey]
          return (a === b ? 0 : a > b ? 1 : -1) * order
        })
      }
      return data
    }
  },
  filters: {
 /*
 This code is taking the first character of a string and making it uppercase
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
    capitalize: function (str) {
      return str.charAt(0).toUpperCase() + str.slice(1)
    }
  },
  methods: {
 /*
 This code is setting the sortKey to key and then changing the value of sortOrders[key] by multiplying it by  1.
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
    sortBy: function (key) {
      this.sortKey = key
      this.sortOrders[key] = this.sortOrders[key] * -1
    }
  }
})

// bootstrap the demo
var demo = new Vue({
  el: '#demo',
  data: {
    searchQuery: '',
    gridColumns: ['name', 'power'],
    gridData: [
      { name: 'Chuck Norris', power: Infinity },
      { name: 'Bruce Lee', power: 9000 },
      { name: 'Jackie Chan', power: 7000 },
      { name: 'Jet Li', power: 8000 }
    ]
  }
})
