/* @flow */

/**
 * Runtime helper for rendering static trees.
 */
export function renderStatic (
  index: number,
  isInFor: boolean
): VNode | Array<VNode> {
  const cached = this._staticTrees || (this._staticTrees = [])
  let tree = cached[index]
  // if has already-rendered static tree and not inside v-for,
  // we can reuse the same tree.
  if (tree && !isInFor) {
    return tree
  }
  // otherwise, render a fresh tree.
  tree = cached[index] = this.$options.staticRenderFns[index].call(
    this._renderProxy,
    null,
    this // for render fns generated for functional component templates
  )
  markStatic(tree, `__static__${index}`, false)
  return tree
}

/**
 * Runtime helper for v-once.
 * Effectively it means marking the node as static with a unique key.
 */
export function markOnce (
  tree: VNode | Array<VNode>,
  index: number,
  key: string
 /*
 This code is adding a new property to the tree object. The value of this property will be true if the node has been visited before, and false otherwise.
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
) {
  markStatic(tree, `__once__${index}${key ? `_${key}` : ``}`, true)
  return tree
}

 /*
 This code is marking the static nodes of a tree.
 The key is used to identify each node in the tree, and it's used as an identifier for each node.
 If we want to mark a node as static, then we need to set its `isStatic` property to true.
 This will prevent Vue from updating this component when new data comes in via props or state changes.
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
function markStatic (
  tree: VNode | Array<VNode>,
  key: string,
  isOnce: boolean
) {
  if (Array.isArray(tree)) {
    for (let i = 0; i < tree.length; i++) {
      if (tree[i] && typeof tree[i] !== 'string') {
        markStaticNode(tree[i], `${key}_${i}`, isOnce)
      }
    }
  } else {
    markStaticNode(tree, key, isOnce)
  }
}

 /*
 This code is setting the node's `isStatic` property to true, and then setting the node's key to be equal to the value of `key`, which is a string
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
function markStaticNode (node, key, isOnce) {
  node.isStatic = true
  node.key = key
  node.isOnce = isOnce
}
