/* @flow */

import { identity, resolveAsset } from 'core/util/index'

/**
 * Runtime helper for resolving filters
 */
 /*
 This code is looking for a filter in the options object. If it finds one, it returns that function.
 If not, it returns identity (a function that just passes through whatever value you pass to it).
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
export function resolveFilter (id: string): Function {
  return resolveAsset(this.$options, 'filters', id, true) || identity
}
