/* @flow */

import type VNode from 'core/vdom/vnode'

/**
 * Runtime helper for resolving raw children VNodes into a slot object.
 */
 /*
 This code is taking the children of a component and mapping them to an object with keys that are the slot names
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
export function resolveSlots (
  children: ?Array<VNode>,
  context: ?Component
 /*
 This code is doing the following.
  It iterates through each child of the vnode and checks if it's a template node or not.
  If it is, then we push all its children to an array called `slot`.
  Otherwise, we push that child to an array called `default` which will be used as fallback in case no slot name was provided by user.
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
): { [key: string]: Array<VNode> } {
  if (!children || !children.length) {
    return {}
  }
  const slots = {}
  for (let i = 0, l = children.length; i < l; i++) {
    const child = children[i]
    const data = child.data
    // remove slot attribute if the node is resolved as a Vue slot node
    if (data && data.attrs && data.attrs.slot) {
      delete data.attrs.slot
    }
    // named slots should only be respected if the vnode was rendered in the
    // same context.
    if ((child.context === context || child.fnContext === context) &&
      data && data.slot != null
    ) {
      const name = data.slot
      const slot = (slots[name] || (slots[name] = []))
      if (child.tag === 'template') {
        slot.push.apply(slot, child.children || [])
      } else {
        slot.push(child)
      }
    } else {
      (slots.default || (slots.default = [])).push(child)
    }
  }
  // ignore slots that contains only whitespace
  for (const name in slots) {
    if (slots[name].every(isWhitespace)) {
      delete slots[name]
    }
  }
  return slots
}

 /*
 This code is checking if the node is a comment and not an async factory. If it's a comment, then we know that it's whitespace.
 If it isn't, then we check to see if the text of the node equals ' '. If so, then this means that there are no children in this VNode and therefore whitespace.
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
function isWhitespace (node: VNode): boolean {
  return (node.isComment && !node.asyncFactory) || node.text === ' '
}
