/* @flow */

 /*
 This code is doing the following.
  It's wrapping the code in a function that returns an object with two properties, `_b` and `tag`.
  The first property is a function that takes three parameters, `code`, `tag`, and `dir`.
    The second parameter is an object containing all of the modifiers for this directive. This includes both prop and sync modifiers. If there are no modifiers then it will be undefined.
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
export default function bind (el: ASTElement, dir: ASTDirective) {
  el.wrapData = (code: string) => {
    return `_b(${code},'${el.tag}',${dir.value},${
      dir.modifiers && dir.modifiers.prop ? 'true' : 'false'
    }${
      dir.modifiers && dir.modifiers.sync ? ',true' : ''
    })`
  }
}
