/* @flow */

import { mergeOptions } from '../util/index'

 /*
 This code is adding a method to the Vue class
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
export function initMixin (Vue: GlobalAPI) {
  Vue.mixin = function (mixin: Object) {
    this.options = mergeOptions(this.options, mixin)
    return this
  }
}
