/* @flow */

import { toArray } from '../util/index'

 /*
 This code is doing the following.
  It's creating a new array called `_installedPlugins` if it doesn't exist yet.
  If the plugin has already been installed, we don't want to install it again so we check that with an indexOf method and return this Vue instance.
  We then push the plugin into our _installedPlugins array using .push() method on our _installedPlugins variable.
 - generated by stenography autopilot [ 🚗👩‍✈️ ] 
 */
export function initUse (Vue: GlobalAPI) {
  Vue.use = function (plugin: Function | Object) {
    const installedPlugins = (this._installedPlugins || (this._installedPlugins = []))
    if (installedPlugins.indexOf(plugin) > -1) {
      return this
    }

    // additional parameters
    const args = toArray(arguments, 1)
    args.unshift(this)
    if (typeof plugin.install === 'function') {
      plugin.install.apply(plugin, args)
    } else if (typeof plugin === 'function') {
      plugin.apply(null, args)
    }
    installedPlugins.push(plugin)
    return this
  }
}
